version: "3.9"

services:
  backend:
    build: ./backend
    ports:
      - "3000:3000"
    env_file:
      - ./backend/.env
    restart: always
    depends_on:
      - zabbix-server
  environment:
    ZBX_SERVER_HOST: zabbix-server

  frontend:
    build: ./frontend
    ports:
      - "4200:80"
    depends_on:
      - backend
      - zabbix-server
    restart: always
environment:
  ZBX_SERVER_HOST: zabbix-server
